 # bonjour.yml
name: Bonjour
on:
  - push  
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - run: docker image build --tag="${IMAGE_NAME}" ./
      # Modification de la commande run pour inclure le montage du volume et le workdir
      - run: docker container run --volume="$(pwd)":"$(pwd)" --workdir="/app" "${IMAGE_NAME}" npm run lint